account/urls.py
from django.conf.urls import url, include
from account import views

app_name = 'auth'

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),  # 登陆
    url(r'^register/$', views.RegisterView.as_view(), name='register'),  # 注册
    url(r'^logout/$', views.logout_access, name='logout'),  # 登出
    url(r'^retrieve/$', views.retrieve_access, name='retrieve'),  # 找回密码
    url(r'^active/(?P<active_code>.*)/', views.activeUser_access, name="activeuser"),  # 注册账号邮箱验证
    url(r'^auth_retrieve/$', views.auth_retrieve, name='auth_retrieve'),  # 找回密码验证
    url(r'^new_password/$', views.new_password_access, name='new_password'),  # 密码修改操作
    url(r'^update_code/$', views.updateCode_access, name='updatecode'),  # 重新获取注册账号邮箱验证码
    url(r'^setpass/(?P<usercode>.*)/$', views.setthisPass, name='setthispass'),
    url(r'^login/oauth2/', include('OAuth2.urls'), name='oauth2')
]

api/urls.py
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

from api import views
from api.WareApp.getWareApp import getWare
from api.router import routerLogical, routerModel, RouterMethodPrivate, RouterMethodPublic, RouterModelPrivate, \
    RouterModelPublic, RouterAdminPrivate

app_name = 'api'

urlpatterns = [
    # 新接口
    path('v2/', views.IndexV2.as_view()),
    path('v2/', include('search.urls')),
    path('v2/authorization/', obtain_jwt_token),
    path('v2/authorization-refresh/', refresh_jwt_token),
    path('v2/authorization-verify/', verify_jwt_token),
    path('v2/model-public/', include(RouterModelPublic.Router().get_router())),
    path('v2/model-private/', include(RouterModelPrivate.Router().get_router())),
    path('v2/method-public/', include(RouterMethodPublic.Router().get_router())),
    path('v2/method-private/', include(RouterMethodPrivate.Router().get_router())),

    path('v2/admin/', include(RouterAdminPrivate.Router().get_router())),

    # 即将废弃 预留兼容老版本接口
    # 获取令牌
    # 刷新令牌
    # 验证令牌
    path('', views.IndexV1.as_view()),
    path('authorization/', obtain_jwt_token),
    path('authorization-refresh/', refresh_jwt_token),
    path('authorization-verify/', verify_jwt_token),
    path('v1/', include(routerModel.RouterModel().get_router())),
    path('v1/logical/', include(routerLogical.RouterModel().get_router())),

    # 废弃
    path('choice/', views.get_Choice, name='choice'),
    path('imageUp/', views.imageUp, name='imageup'),
    path('getWare/', getWare, name='getWare')
]

app/urls.py
from django.conf.urls import url
from django.urls import path
from django.views import generic

from app import views, view
from app.view import app_navaid, AboutView
from app.view.app_navaid import IndexView

app_name = 'app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('details/<int:details_id>/', views.IndexDetailsView.as_view(), name='details'),
    path('details/<int:details_id>/<str:details_slug>/', views.IndexDetailsView.as_view(), name='detailsnew'),
    path('Assortment/<int:class_id>/', views.Assortment.as_view(), name='assortment'),
    path('IndexView/', IndexView.as_view(), name='IndexView'),
    path('about/', generic.TemplateView.as_view(template_name='defaule/about/index.html'), name='about'),
    path('about/us/', generic.TemplateView.as_view(template_name='defaule/about/about.html'), name='us'),

    url(r'^setPlus/$', views.setPlus, name='setPlus'),
    url(r'^contrast/$', views.Contrast, name='contrast'),
    url(r'^sale/$', views.sale, name='sale'),
    url(r'^personal/$', views.personal, name='personal'),
    url(r'^navaid/(\d+)/$', app_navaid.navaid, name='app_navaid'),

    path('pdf/', views.PDF.as_view())

]

home/urls.py
from django.conf.urls import url
from django.urls import path

from home import views

app_name = 'home'

urlpatterns = [
    url(r'^generateOrder_delete/$', views.generateOrder_delete, name='generateOrder_delete'),
    url(r'^address/$', views.address, name='address'),
    url(r'^addaddress/$', views.addAddress, name='addaddress'),
    url(r'^setaddress/$', views.setaddress, name='setaddress'),
    url(r'^deladdress/$', views.deladdress, name='deladdress'),
    url(r'^getaddress/$', views.getAddress, name='getaddress'),
    url(r'^settlement/$', views.Settlement, name='settlement'),
    url(r'^delorider/$', views.delorider, name='delorider'),
    url(r'^getlogistics/$', views.getlogistics, name='getlogistics'),
    url(r'^personal/$', views.personal, name='personal'),
    url(r'^invoice/$', views.Invoice, name='invoice'),
    url(r'^contract/$', views.Contract, name='contract'),
    url(r'^ordercontract1/(\d+)/$', views.OrderContract, name='ordercontract'),

    path('ordercontract/<str:id>/', views.PDFOrderContract.as_view(), name='ordercontract'),
    path('', views.Index.as_view(), name='index'),

    url(r'^getpulContract/$', views.getpulContract, name='getpulContract'),
    url(r'^setContract/$', views.setContract, name='setContract'),
]

lhwill/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.static import serve

from lhwill import views
from lhwill.settings import MEDIA_ROOT
from lhwill.util.AutomaticCollection import ZnanrenSitemaps
from search.views import RestfulSearchView

sitemaps = {
    'WareApp': ZnanrenSitemaps,
}


urlpatterns = [
    path('', include('app.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('error/', views.error_),


    path('admin/', include('managestage.urls')),

    path('auth/', include('account.urls')),
    path('shopping/', include('shopping.urls')),
    path('auth/', include('social_django.urls')),
    path('home/', include('home.urls')),
    url('^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    path('favicon.ico', RedirectView.as_view(url=r'static/favicon.ico', permanent=True)),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('plate/', include('plate.urls'))
    # url(r'^payment/', include('payment.urls'))

]

search/urls.py
from django.urls import path, include
from rest_framework import routers

from search.views import RestfulSearchView

router = routers.DefaultRouter()
router.register('search', RestfulSearchView, base_name='search')

urlpatterns = [
    path('', include(router.urls)),
]

search/models.py
from django.db import models


# 搜索引擎


class GoodsLabelInfo(models.Model):
    '''
    商品标签信息 用于辅助搜索引擎搜索商品
    为商品打标签
    '''
    label = models.CharField(max_length=25, verbose_name='商品标签',
                             help_text='商品标签，每个商品拥有不同的标签。用于定位或标记商品本身')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间', help_text='标签创建时间')
    now_time = models.DateTimeField(auto_now=True, verbose_name='标签更新时间', help_text='标签更新时间')
    key = models.ForeignKey('app.WareApp', verbose_name='关联商品', help_text='关联商品', on_delete=models.CASCADE)

    class Meta:
        ordering = ['add_time']

class GoodsPrefixInfo(models.Model):
    '''
    商品更多聚集信息 包含了商品品牌，商品参数，商品型号等信息
    用于辅助搜索引擎搜索商品
    '''

    key = models.ForeignKey('app.WareApp', verbose_name='关联商品', help_text='关联商品', on_delete=models.CASCADE)

search/views.py
# Create your views here.
from rest_framework.viewsets import ViewSet

from app.models import WareApp
from search.serializers import GoodsImageList
from search.viewsets import RestSearchView


class RestfulSearchView(ViewSet, RestSearchView):
    '''
    搜索商品
    '''
    def get_content_results(self):
        results = []
        r = super(RestfulSearchView, self).get_content_results()
        for item in r:
            results.append({
                **item,
                'image': GoodsImageList(WareApp.objects.get(id=item['id']).images_set.filter(), many=True).data
            })
            pass
        return results
    pass

templates/defaule_back/app/contrast.html
{% extends 'defaule/temp/top-nav.ht' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
    {% if site_name %}
        {% if site_tags %}
            <title>{{site_name}} - {{site_tags}}</title>
        {% else %}
            <title>{{site_name}}</title>
        {% endif %}
    {% else %}
        {% if site_tags %}
            <title>{{site_tags}}</title>
        {% else %}
            <title>你好粗心，怎么没有设置标题呢？</title>
        {% endif %}
    {% endif %}
{% endblock title %}

<!-- SEO优化 -->
{% block seo %}
{% endblock seo %}

<!-- CSS样式 -->

{% block css %}
    {% include 'defaule/temp/css.ht' %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/htmleaf-demo.css' %}">
    <link rel="stylesheet" href="{%static 'iCheck/square/blue.css'%}">
    <style>
            .users-list li:hover{
                box-shadow: 0 15px 30px rgba(0,0,0,0.1);
                transform: translate3d(0,-2px,0);
            }
            .users-list li{
                width: 22%;
                height: 365px;
                margin-bottom: 20px;
                margin-right: 4%;
                transition: all .2s linear;
                background: white;
            }
            .users-list li:nth-of-type(4){
                margin-right: 0;
            }
            .boxborder:hover{
                color:#2489c5 ;
            }
            .addgoods{
                width: 100%;
                box-sizing: border-box;
            }
            .addgoods-li{
                width: 22%;
                height: 100px;
                float: left;
                border-right: 1px solid #2489c5 ;
            }
            .addgoods-li-five{
                width: 12%;
                border: none;
                text-align: center;
                height: 100px;
                float: right;
                border-right:none ;
            }
            #tab_1{
                height: 100px;
            }
            .alertwindow{
                width: 1200px;
                z-index: 1000;
                position: fixed;
                bottom: 0;
                margin: 0 auto;
                display: none;
            }
            .col-md-10{
                padding-left: 0 !important;
                padding-right: 0 !important;
            }
            .contrastBox{
            	width: 100%;
            	height: 500px;
            	background: #FFFFFF;
            	margin-bottom: 20px;
            }
            .contrastBox tr{
            	height: 50px;
            }
            .contrastBox tr td{
            	text-align: center;
            	border: 1px solid #e4e4e4;
            }
            .navbar-nav>.user-menu>.dropdown-menu>li.user-header{
				height: 160px !important;
			}
    </style>
{% endblock css %}

<!-- 导航栏-->
{% block navbar %}
    <div class="container">
        <div class="navbar-header">
            <a href="{% url 'app:index' %}" class="navbar-brand"><b>{{site_name}}</b></a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <i class="fa fa-bars"></i>
            </button>
        </div>
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'app:index' %}">首页</a></li>
                {% for var1 in navigation %}
                    <li><a href="{{var1.url}}">{{var1.name}}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    {% if username %}
                        <a href="{% url 'home:index' %}">
                            <span class="hidden-xs"> 我的订单 </span>
                        </a>
                    {% endif %}
                </li>

                {% if not username %}
                <li class="dropdown user user-menu">
                    <a href="{% url 'auth:oauth2:login_zycg' %}" class="dropdown-toggle">
                        <img src="http://mall.zycg.gov.cn/home/images/yc.png" class="user-image" alt="User Image">
                        <span class="hidden-xs">央采登录</span>
                    </a>
                </li>
                {% endif %}
                <li class="dropdown user user-menu">
                    {% if username %}
                        <a href="{% url 'auth:logout' %}" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% static 'images/user/user2-160x160.jpg' %}" class="user-image" alt="User Image">
                            <span class="hidden-xs"> {{username}} </span>
                        </a>
                    {% else %}
                        <a href="{% url 'auth:login' %}" class="dropdown-toggle">
                            <span class="hidden-xs">请登陆</span>
                        </a>
                    {% endif %}
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src={% static "images/user/user2-160x160.jpg" %} class="img-circle" alt="User Image">
                            <p>
                                <small>{{site_name}} 欢迎您 </small>
                            </p>
                        </li>
                        <!-- <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                        </li> -->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{% url 'home:index' %}" class="btn btn-default btn-flat">我的订单</a>
                            </div>
                            <div class="pull-right">
                                <a href="{% url 'auth:logout' %}" class="btn btn-default btn-flat">退出登录</a>
                            </div>
                        </li>
                    </ul>
                </li>

                {% if not username %}
                <li class="dropdown user user-menu">
                    <a href="{% url 'auth:register' %}" class="dropdown-toggle">
                        <span class="hidden-xs">立即注册</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock navbar %}

{% block content_wrapper %}
    <div class="row">
        <div class="container box-body" style="margin-top: 20px;">
            <div class="col-md-6 col-md-offset-3">
                <form action="{% url 'app:search' %}" method="GET">
                    <div class="input-group">
                        <input name="search" type="text" {% if error %}value="{{search}}"{% else %}{% if search %} placeholder="{{search}}" {% endif %}{% endif %} class="form-control">
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-info btn-flat">搜索</button>
                        </span>
                    </div>
                </form>

                <div id="hotwords" class="haveline" style="margin-top: 2px;">
                    {% for var1 in statistics %}
                        <a>{{var1.name}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>


        <div class="zxr_nav">
            <div class="nav_ten"  style="margin-top: 43px;">
                <div id="logo" class="logo">
                    <div class="logo_extend" clstag="h|keycount|head|logo_02" style="display: block;">
                        <a href="" style="display: block; width: auto; height: 170px; background: #fff;" target="_blank">
                            <img src="/static/Logosc_2000x1500.png" style="margin: auto; display: block; width: 170px; height: 150px;">
                        </a>
                    </div>
                </div>
                <div class="quanbu_zxr">
                    <!--div class="quanbu_zxr1"> 全部商品分类</div-->
                    <ul class="ul" style="margin-bottom: 0px; margin-left: 205px;">
                        {% for var1 in navigation_two %}
                        <li><a href={{var1.url}}>{{var1.name}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                {% if error %}
                <div class="callout callout-warning" style="margin-top:50px; margin-bottom: 50px;">
                    <h4 style="color: #fff; margin-top: 20px;">{{error}}, 推荐您搜索 {{search}}</h4>
                </div>


                {% endif %}
            </div>
        </div>
    </div>

    <br>
    <!--对比框-->
    <div class="container " style="padding: 0;">
		<table class="contrastBox">
			<tr style="height: 180px;">
				<td style="width:12%;">商品信息</td>
                {% for var1 in warelist %}
				<td style="width:22% ;">
					<img src="{{var1.image}}" width="160px" height="160px"/>
					<p>{{var1.name}}</p>
					<p style="color: red;margin: 0;">￥ {{var1.money}}</p>
				</td>
                {% endfor %}
			</tr>
			<tr>
				<td style="width:12%;"><span>品牌</span></td>
                {% for var1 in warelist %}
				<td style="width:22% ;"><span>{{var1.brands}}</span></td>
                {% endfor %}
			</tr>
			<tr>
				<td style="width:12%;"><span>产品型号</span></td>
				{% for var1 in warelist %}
                <td style="width:22% ;"><span>{{var1.model}}</span></td>
                {% endfor %}
			</tr>
			<tr>
				<td style="width:12%;"><span>颜色类型</span></td>
				{% for var1 in warelist %}
                <td style="width:22% ;"><span>{{var1.colorType}}</span></td>
                {% endfor %}
			</tr>
		</table>
	</div>



{% endblock content_wrapper %}

{% block top_script %}
{% endblock top_script %}



{% block script %}
    {% include 'defaule/temp/script.ht' %}

{% endblock script %}

templates/defaule_back/app/search-text.html
<html>
<head>
    <title>全文检索</title>
</head>
<body>
<form method='get' action="/search/" target="_blank">
    <input type="text" name="q">
    <br>
    <input type="submit" value="查询">
</form>
</body>
</html>