account/urls.py
from django.conf.urls import url, include
from account import views

app_name = 'auth'

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),  # 登陆
    url(r'^register/$', views.RegisterView.as_view(), name='register'),  # 注册
    url(r'^logout/$', views.logout_access, name='logout'),  # 登出
    url(r'^retrieve/$', views.retrieve_access, name='retrieve'),  # 找回密码
    url(r'^active/(?P<active_code>.*)/', views.activeUser_access, name="activeuser"),  # 注册账号邮箱验证
    url(r'^auth_retrieve/$', views.auth_retrieve, name='auth_retrieve'),  # 找回密码验证
    url(r'^new_password/$', views.new_password_access, name='new_password'),  # 密码修改操作
    url(r'^update_code/$', views.updateCode_access, name='updatecode'),  # 重新获取注册账号邮箱验证码
    url(r'^setpass/(?P<usercode>.*)/$', views.setthisPass, name='setthispass'),
    url(r'^login/oauth2/', include('OAuth2.urls'), name='oauth2')
]

api/urls.py
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

from api import views
from api.WareApp.getWareApp import getWare
from api.router import routerLogical, routerModel, RouterMethodPrivate, RouterMethodPublic, RouterModelPrivate, \
    RouterModelPublic, RouterAdminPrivate

app_name = 'api'

urlpatterns = [
    # 新接口
    path('v2/', views.IndexV2.as_view()),
    path('v2/', include('search.urls')),
    path('v2/authorization/', obtain_jwt_token),
    path('v2/authorization-refresh/', refresh_jwt_token),
    path('v2/authorization-verify/', verify_jwt_token),
    path('v2/model-public/', include(RouterModelPublic.Router().get_router())),
    path('v2/model-private/', include(RouterModelPrivate.Router().get_router())),
    path('v2/method-public/', include(RouterMethodPublic.Router().get_router())),
    path('v2/method-private/', include(RouterMethodPrivate.Router().get_router())),

    path('v2/admin/', include(RouterAdminPrivate.Router().get_router())),

    # 即将废弃 预留兼容老版本接口
    # 获取令牌
    # 刷新令牌
    # 验证令牌
    path('', views.IndexV1.as_view()),
    path('authorization/', obtain_jwt_token),
    path('authorization-refresh/', refresh_jwt_token),
    path('authorization-verify/', verify_jwt_token),
    path('v1/', include(routerModel.RouterModel().get_router())),
    path('v1/logical/', include(routerLogical.RouterModel().get_router())),

    # 废弃
    path('choice/', views.get_Choice, name='choice'),
    path('imageUp/', views.imageUp, name='imageup'),
    path('getWare/', getWare, name='getWare')
]

app/urls.py
from django.conf.urls import url
from django.urls import path
from django.views import generic

from app import views, view
from app.view import app_navaid, AboutView
from app.view.app_navaid import IndexView

app_name = 'app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('details/<int:details_id>/', views.IndexDetailsView.as_view(), name='details'),
    path('details/<int:details_id>/<str:details_slug>/', views.IndexDetailsView.as_view(), name='detailsnew'),
    path('Assortment/<int:class_id>/', views.Assortment.as_view(), name='assortment'),
    path('IndexView/', IndexView.as_view(), name='IndexView'),
    path('about/', generic.TemplateView.as_view(template_name='defaule/about/index.html'), name='about'),
    path('about/us/', generic.TemplateView.as_view(template_name='defaule/about/about.html'), name='us'),

    url(r'^setPlus/$', views.setPlus, name='setPlus'),
    url(r'^contrast/$', views.Contrast, name='contrast'),
    url(r'^sale/$', views.sale, name='sale'),
    url(r'^personal/$', views.personal, name='personal'),
    url(r'^navaid/(\d+)/$', app_navaid.navaid, name='app_navaid'),

    path('pdf/', views.PDF.as_view())

]

lhwill/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.static import serve

from lhwill import views
from lhwill.settings import MEDIA_ROOT
from lhwill.util.AutomaticCollection import ZnanrenSitemaps
from search.views import RestfulSearchView

sitemaps = {
    'WareApp': ZnanrenSitemaps,
}


urlpatterns = [
    path('', include('app.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('error/', views.error_),


    path('admin/', include('managestage.urls')),

    path('auth/', include('account.urls')),
    path('shopping/', include('shopping.urls')),
    path('auth/', include('social_django.urls')),
    path('home/', include('home.urls')),
    url('^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    path('favicon.ico', RedirectView.as_view(url=r'static/favicon.ico', permanent=True)),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('plate/', include('plate.urls'))
    # url(r'^payment/', include('payment.urls'))

]

plate/urls.py
from django.urls import path, re_path
from plate.views import IndexView

app_name = 'plate'

urlpatterns = [
    path('<int:id>/<str:slug>/', IndexView.as_view(), name='index')
]

shopping/urls.py
from django.conf.urls import url
from django.urls import path

from shopping import views, view
from django.contrib.auth.decorators import login_required, permission_required

from shopping.view.IndexCartToolpApi import CartToolp

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='shopping'),
    url(r'^CartToolp/$', view.IndexCartToolpApi.CartToolp.as_view(), name='CartToolp'),
    url(r'^settleAccounts/$', views.PlaceOrderView.as_view(), name='settleAccounts'),
    path('BuyGoods/<int:app_id>/', views.BuyGoods.as_view(), name='BuyGoods'),

    path('PlaceOrder/', views.PlaceOrderView.as_view(), name='PlaceOrderView'),
    path('PlaceOrder/<int:ware_id>/', views.PlaceOrderView.as_view(), name='PlaceOrderView'),
    path('success/<str:order_id>/', views.SuccessView.as_view(), name='success'),
]

plate/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone
from slugify import slugify


class plateModels(models.Model):
    '''
    导航页面 [涵盖导航 二级导航]

    类似于 文章等
    '''
    name = models.CharField(max_length=200, verbose_name='板块名称')
    slug = models.SlugField(max_length=200, verbose_name='slugify(name)')

    time_add = models.DateTimeField(auto_now_add=True)
    time_now = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if not self.time_add:
            self.time_add = timezone.now()

        super(plateModels, self).save(*args, **kwargs)
        pass

    def get_absolute_url(self):
        return reverse('plate:index', args=[self.id, self.slug])



    def __str__(self):
        return self.name
    pass


class plateContent(models.Model):
    '''页面板块'''
    name = models.CharField(max_length=200, verbose_name='板块标题')
    content = models.ForeignKey('app.Classification_There', on_delete=models.SET_NULL, null=True, verbose_name='')
    number = models.IntegerField(default=10, verbose_name='商品查询数量')
    key = models.ForeignKey(plateModels, on_delete=models.CASCADE, null=True)

    time_add = models.DateTimeField(auto_now_add=True)
    time_now = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.time_add:
            self.time_add = timezone.now()

        super(plateContent, self).save(*args, **kwargs)
        pass

    def get_wareappprefix_set(self):
        return self.content.wareappprefix_set.filter()[:10]

plate/views.py
# Create your views here.
from django.http import HttpResponse

from app.models import WareAppPrefix
from app.util.classify import getClassify
from lhwill.util.log import log
from lhwill.view import AppGenric
from lhwill.view.HttpCodeError import get_object_or_404
from plate import models

logger = log(globals())


class IndexView(AppGenric.AppTemplateView):
    template_name = 'defaule/plate/index.html'
    template_mobile_name = 'defaule/m/plate/index.html'

    _context_data = True
    _context_data_response = None

    def get_context_data(self, **kwargs):

        plat = get_object_or_404(self.request, models.plateModels, id=kwargs['id'], slug=kwargs['slug'])
        if type(plat) == HttpResponse:
            self._context_data = False
            self._context_data_response = plat
        else:
            kwargs['Content'] = models.plateContent.objects.filter(key=plat)
            kwargs['Models'] = plat
            kwargs.update(getClassify())

        return kwargs

    def render_to_response(self, context, **response_kwargs):
        response_kwargs.setdefault('content_type', self.content_type)

        if not self._context_data:
            logger.i(self._context_data_response)
            return self._context_data_response

        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            using=self.template_engine,
            **response_kwargs
        )

    pass

templates/defaule_back/plate/index.html
{% extends 'defaule/temp/top-nav.html' %}
{% load thumbnail %}
{% load staticfiles %}
{% load tags %}

{% block title %}
    <title>{{ site_name }} - {{ site_tags }}</title>
{% endblock title %}

<!-- SEO优化 -->
{% block seo %}
{% endblock seo %}

<!-- CSS样式 -->

{% block css %}
    <link rel="stylesheet" href="{% static 'css/assortmentSearch.css' %}">

    <style type="text/css">

        /* 商品 */
        .subplate-ant.antx > .ware-box {
            border: unset !important;
        }

        .subplate-ant.antx > .ware-box > .ware-box-main {
            width: 85px;
            background: #00c0ef;
            margin: 0px 8px 0px 0px;
        }

        .subplate-ant.antx > .ware-box > .ware-box-main > a {
            color: #fff;
            font-size: 12px;
            position: absolute;
            margin: 3px 0 0 18px;
        }

        .subplate-ant.antx > .ware-box > .ware-box-bout.warecart {
            width: 102px;
            height: 23px;
            margin: 0px 0 0 -8px;
            border: 1px solid #76e2f94f !important;
        }

        .subplate-ant.antx > .ware-box > .ware-box-bout.warecart > a {
            margin: 2px 0px 0px 30px;
        }

        .subplate-ant.antx > .ware-box > .ware-box-bout.warecart > a > i {
            font-size: 16px;
            margin: 0px 0px 0px -20px;
        }

        .subplate-ant.antx > .text-name {
            margin-bottom: unset;
        }

        .plate-ant > .antx {
            height: 330px !important;
        }


        .subplate-ant > .text-name {
            white-space: nowrap !important;
        }

        .box-with-plate {
            width: 1200px;
            height: 39px;
            background: #fff;
            margin: 0 0 10px 5px;
            border-left: 5px solid #5bc0de;
            border-radius: 10px 0 10px 0;
            border-top: 1px solid #5bc0de;

        }



        .content-wrapper > div.row {
            background: url(/static/images/plate.jpg) no-repeat center center fixed;
            background-size: 100%;
        }

        .content-wrapper > div.row.white {
            background: #fff;
        }


    </style>
{% endblock css %}



{% block content_wrapper %}


    <!-- 板块专区 -->
    <div class="content pl m-auto">
        <div class="row">
            <div class="box-filter">
                <div class="box-filter-header clearfix">
                    <ul class="box-filter-header-ul ">
                        <li><a href="{% url 'app:index' %}">首页</a></li>
                        <li style="margin: 0 2px 0 0;"> &gt;</li>
                        <li><a href="{% url 'app:index' %}">导航</a></li>
                        <li style="margin: 0 2px 0 0;"> &gt;</li>
                        <li>{{ search }}</li>
                    </ul>
                </div>
            </div>
        </div>

        {% for var1 in Content %}
        <!-- 展示5个商品 -->
        <div class="plate plate-ant">

            <div class="box-header box-with-plate">
                <h3 class="box-title">{{var1.name}}</h3>
                <div class="pull-right"><a target="plate" href="{% url 'app:assortment' 3 %}?search={{ var1.name }}">更多 &nbsp;<i class="fa fa-caret-right text-info"></i></a></div>
            </div>

            {% for ware in var1.get_wareappprefix_set %}

            <div class="subplate-ant antx">
                <a target="wareApp" href="{% url 'app:details' ware.wareApp_key.id %}" title="">
                    {% thumbnail ware.wareApp_key.get_image_url "220x220" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                             style="border-radius: 5px; margin-top: 15px !important;">
                    {% endthumbnail %}
                </a>
                <div class="text-price">￥{{ware.wareApp_key.money}}</div>
                <div class="text-name">
                    <a target="wareApp" href="{% url 'app:details' ware.wareApp_key.id %}" title="">
                        {{ware.wareApp_key.name}}
                    </a>
                </div>

                <div class="ware-box">
                    <div class="ware-box-main">
                        <a target="wareApp" href="{% url 'app:details' ware.wareApp_key.id %}"  title="">查看商品</a>
                    </div>
                    <div class="ware-box-bout warecart" id="{{ ware.wareApp_key.id }}">
                        <a href="" title=""><i class="fa fa-cart-plus"></i>加入购物车</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        {% endfor %}



    </div>
{% endblock content_wrapper %}


{% block script %}

    <script>
        function goLogin() {
            window.location.href = '{% url "auth:login" %}'
        }

        $('.warecart').on('click', function (event) {
            event.preventDefault();
            /* Act on the event */

            var data = {
                "id": this.id,
                "number": 1
            }

            $.ajax({
                url: "{% url 'shop:shopping' %}",
                type: 'POST',
                dataType: 'json',
                data: data,
            })
                .done(function (data) {
                    toastr.success("以添加到购物车");
                    console.log("id  " + data.data.id);
                    console.log("leas  " + data.data.leas);
                    console.log("number  " + data.data.number);
                    console.log("money  " + data.data.money);
                })
                .fail(function (data) {
                    console.log(String(data.responseText).split(' - ')[1].split('</title>')[0]);
                    if (String(data.responseText).split(' - ')[1].split('</title>')[0] == '登录') {
                        goLogin();
                    } else {
                        toastr.error('啊呀，发生错误了。请截图联系客服哦')
                        toastr.error(data.responseText)
                    }
                    ;
                })
                .always(function () {
                    console.log("complete");
                });
        });


        function removeByValue(arr, val) {
            for (var i = 0; i < arr.length; i++) {
                console.log('arr ' + arr[i]);
                if (arr[i] == val) {
                    arr.splice(i, 1);
                    break;
                }
            }
        }


    </script>
{% endblock script %}