api/urls.py
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

from api import views
from api.WareApp.getWareApp import getWare
from api.router import routerLogical, routerModel, RouterMethodPrivate, RouterMethodPublic, RouterModelPrivate, \
    RouterModelPublic, RouterAdminPrivate

app_name = 'api'

urlpatterns = [
    # 新接口
    path('v2/', views.IndexV2.as_view()),
    path('v2/', include('search.urls')),
    path('v2/authorization/', obtain_jwt_token),
    path('v2/authorization-refresh/', refresh_jwt_token),
    path('v2/authorization-verify/', verify_jwt_token),
    path('v2/model-public/', include(RouterModelPublic.Router().get_router())),
    path('v2/model-private/', include(RouterModelPrivate.Router().get_router())),
    path('v2/method-public/', include(RouterMethodPublic.Router().get_router())),
    path('v2/method-private/', include(RouterMethodPrivate.Router().get_router())),

    path('v2/admin/', include(RouterAdminPrivate.Router().get_router())),

    # 即将废弃 预留兼容老版本接口
    # 获取令牌
    # 刷新令牌
    # 验证令牌
    path('', views.IndexV1.as_view()),
    path('authorization/', obtain_jwt_token),
    path('authorization-refresh/', refresh_jwt_token),
    path('authorization-verify/', verify_jwt_token),
    path('v1/', include(routerModel.RouterModel().get_router())),
    path('v1/logical/', include(routerLogical.RouterModel().get_router())),

    # 废弃
    path('choice/', views.get_Choice, name='choice'),
    path('imageUp/', views.imageUp, name='imageup'),
    path('getWare/', getWare, name='getWare')
]

lhwill/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.static import serve

from lhwill import views
from lhwill.settings import MEDIA_ROOT
from lhwill.util.AutomaticCollection import ZnanrenSitemaps
from search.views import RestfulSearchView

sitemaps = {
    'WareApp': ZnanrenSitemaps,
}


urlpatterns = [
    path('', include('app.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('error/', views.error_),


    path('admin/', include('managestage.urls')),

    path('auth/', include('account.urls')),
    path('shopping/', include('shopping.urls')),
    path('auth/', include('social_django.urls')),
    path('home/', include('home.urls')),
    url('^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    path('favicon.ico', RedirectView.as_view(url=r'static/favicon.ico', permanent=True)),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('plate/', include('plate.urls'))
    # url(r'^payment/', include('payment.urls'))

]

managestage/urls.py
from django.conf.urls import url
from django.urls import path

from managestage import views
from managestage.view import AdmUser, AdmComplete, AdmCommodity, AdmSector, AdmPage, AdmOrder, AdmPlate

app_name = 'admins'

urlpatterns = [
    # 全局-站点设置
    url(r'^complete/$', views.plate.AdmComplete, name='complete'),
    url(r'^complete/set_system/$', AdmComplete.set_system, name='set_system'),
    url(r'^complete/set_maintain/$', AdmComplete.set_maintain, name='set_maintain'),
    url(r'^complete/seosetup/$', AdmComplete.seosetup, name='seosetup'),
    url(r'^complete/set_mailsmtp/$', AdmComplete.set_mailsmtp, name='set_mailsmtp'),
    url(r'^complete/send_email/$', AdmComplete.send_email, name='send_email'),
    url(r'^complete/set_appid/$', AdmComplete.set_appid, name='set_appid'),
    url(r'^complete/partysetup/$', AdmComplete.partysetup, name='partysetup'),
    url(r'^complete/setclassify_orthere/$', AdmComplete.setclassify_orthere, name='setclassify_orthere'),

    # 用户-用户管理
    path('user/', views.UserView.as_view(), name='user'),
    url(r'^user/get_username/$', AdmUser.get_username, name='get_username'),
    url(r'^user/del_user/$', AdmUser.del_user, name='del_user'),
    url(r'^user/set_email/$', AdmUser.set_email, name='set_email'),
    url(r'^user/set_username/$', AdmUser.set_username, name='set_username'),
    url(r'^user/set_password/$', AdmUser.set_password, name='set_password'),
    url(r'^user/add_user/$', AdmUser.add_user, name='add_user'),
    url(r'^user/set_admin/$', AdmUser.set_admin, name='set_admin'),
    url(r'^user/examine/$', AdmUser.examine, name='examine'),
    url(r'^user/set_examine/$', AdmUser.set_examine, name='set_examine'),

    # 商品
    url(r'^commodity/$', views.plate.AdmCommodity, name='commodity'),
    url(r'^commodity/(\d+)/$', views.plate.AdmCommodity, name='commodity'),

    path('commodity/create/', AdmCommodity.ArticleRelease.as_view(), name='ware'),
    path('commodity/create/<int:app_id>/<int:app_unix>/', AdmCommodity.ArticleRelease.as_view(), name='ware'),
    path('commodity/create/info/<int:app_id>/<int:app_unix>/<int:app_there>/',
         AdmCommodity.ArticleInfoRelease.as_view(), name='info'),

    url(r'^commodity/create/parameter/(\d+)/(\d+)/$', AdmCommodity.parameter, name='parameter'),

    url(r'^commodity/create/createParameter/$', AdmCommodity.add_Parameter, name='createParameter'),  # aaaaa
    url(r'^commodity/online/(\d+)/(\d+)/$', AdmCommodity.online, name='online'),
    url(r'^commodity/add_mode/$', AdmCommodity.add_mode, name='addmode'),
    url(r'^commodity/add_choice/$', AdmCommodity.add_choice, name='add_choice'),
    url(r'^commodity/release/(\d+)/(\d+)/$', AdmCommodity.release, name='release'),
    url(r'^commodity/set_online/$', AdmCommodity.set_online, name='set_online'),
    url(r'^commodity/deletle/$', AdmCommodity.del_ware, name='del_ware'),
    url(r'^commodity/deletle/(\d+)/$', AdmCommodity.del_ware, name='del_ware'),
    url(r'^commodity/stay/$', AdmCommodity.stay, name='stay'),
    url(r'^commodity/stay/(\d+)$', AdmCommodity.stay, name='stay'),
    url(r'^commodity/import/$', AdmCommodity.import_Wareapp, name='import'),

    path('commodity/ClassZycg/', AdmCommodity.ClassZycg.as_view(), name='ClassZycg'),
    path('commodity/SettupView/', AdmCommodity.SettupView.as_view(), name='SettupView'),
    path('Initialization/', AdmCommodity.Initialization.as_view(), name='Initialization'),

    url(r'^importfile/$', AdmCommodity.importfile, name='importfile'),

    url(r'^commodity/setupcommod/$', AdmCommodity.SetupCommod, name='setupcommod'),
    url(r'^get_classModels/$', AdmCommodity.get_classModels, name='get_classModels'),
    url(r'^get_ClassifyTwo/$', AdmCommodity.get_ClassifyTwo, name='get_classifyTwo'),

    # 板块
    url(r'^sector/$', views.plate.AdmSector, name='sector'),
    url(r'^sector/get_ware/$', AdmSector.get_ware, name='get_ware'),
    url(r'^sector/add_sector/$', AdmSector.add_sector, name='add_sector'),
    url(r'^sector/set_addSector/$', AdmSector.set_addSector, name='set_addSector'),
    url(r'^sector/set_brock/$', AdmSector.set_brock, name='set_brock'),
    url(r'^sector/add_label/$', AdmSector.add_label, name='add_label'),
    url(r'^sector/get_label/$', AdmSector.get_label, name='get_label'),
    url(r'^sector/set_label/$', AdmSector.set_label, name='set_label'),
    url(r'^sector/del_brock/$', AdmSector.del_brock, name='del_brock'),
    url(r'^sector/add_WareAppBrock/$', AdmSector.add_WareAppBrock, name='add_WareAppBrock'),
    url(r'^sector/del_WareAppBrock/$', AdmSector.del_WareAppBrock, name='del_WareAppBrock'),
    url(r'^sector/classify/$', AdmSector.classify.as_view(), name='classify'),
    url(r'^sector/add_classify/$', AdmSector.add_classify, name='add_classify'),
    url(r'^sector/del_classify/$', AdmSector.del_classify, name='del_classify'),
    url(r'^sector/add_classifyLabel/$', AdmSector.add_classifyLabel, name='add_classifyLabel'),
    url(r'^sector/get_classify/$', AdmSector.get_classify, name='get_classify'),
    url(r'^sector/set_classify/$', AdmSector.set_classify, name='set_classify'),
    url(r'^sector/get_classifyLabel/$', AdmSector.get_classifyLabel, name='get_classifyLabel'),
    url(r'^sector/set_classifyLabel/$', AdmSector.set_classifyLabel, name='set_classifyLabel'),
    url(r'^sector/del_classifyLabel/$', AdmSector.del_classifyLabel, name='del_classifyLabel'),
    url(r'^sector/add_classify_two/$', AdmSector.add_classify_two, name='add_classify_two'),
    url(r'^sector/get_classifytwo/$', AdmSector.get_classifytwo, name='get_classifytwo'),
    url(r'^sector/get_classifythere/$', AdmSector.get_classifythere, name='get_classifythere'),
    url(r'^sector/add_classifythere/$', AdmSector.add_classifyThere, name='add_classifyThere'),
    url(r'^sector/set_classifytwo/$', AdmSector.set_classifyTwo, name='set_classifyTwo'),
    url(r'^sector/set_classifythere/$', AdmSector.set_classifyThere, name='set_classifyThere'),
    url(r'^sector/del_classifytwo/$', AdmSector.del_classifyTwo, name='del_classifyTwo'),
    url(r'^sector/del_classifythere/$', AdmSector.del_classifyThere, name='del_classifyThere'),
    url(r'^sector/navigation/$', AdmSector.navigation, name='navigation'),
    url(r'^sector/add_navigation/$', AdmSector.add_Navigation, name='add_navigation'),
    url(r'^sector/add_navigationtwo/$', AdmSector.add_NavigationTwo, name='add_navigationtwo'),
    url(r'^sector/set_navigation/$', AdmSector.set_Navigation, name='set_navigation'),
    url(r'^sector/set_navigationtwo/$', AdmSector.set_NavigationTwo, name='set_navigationtwo'),
    url(r'^sector/del_navigation/$', AdmSector.del_Navigation, name='del_navigation'),
    url(r'^sector/del_navigationTwo/$', AdmSector.del_NavigationTwo, name='del_navigationtwo'),
    url(r'^sector/broadcast/$', AdmSector.broadcast, name='broadcast'),
    url(r'^sector/_add_broadcast/$', AdmSector._add_broadcast, name='_add_broadcast'),
    url(r'^sector/_set_broadcast/$', AdmSector._set_broadcast, name='_set_broadcast'),
    url(r'^sector/del_broadcast/$', AdmSector.del_broadcast, name='del_broadcast'),
    url(r'^sector/setupsearch/$', AdmSector.SetupSearch, name='setupsearch'),
    url(r'^sector/setupparameter/$', AdmSector.setupParameterView, name='setupparameter'),
    url(r'^sector/add_Brand/$', AdmSector.add_Brand, name='add_brand'),
    # ---
    url(r'^sector/add_filter/$', AdmSector.add_filter, name='add_filter'),
    url(r'^sector/parter/$', AdmSector.get_parter, name='get_parter'),
    url(r'^sector/wareparCHOICES/$', AdmSector.get_wareparCHOICES, name='warechoices'),
    path('sector/DiscountView/', AdmSector.DiscountView.as_view(), name='discount'),
    url(r'^sector/adddiscount/$', AdmSector.addDiscount, name='adddiscount'),
    url(r'^sector/getDiscount/$', AdmSector.getDiscount, name='getDiscount'),

    path('sector/searchlevel/', AdmSector.searchLevel.as_view(), name='searchLevel'),

    url(r'^sector/setupprefix/$', AdmSector.SetupPrefix, name='setupprefix'),
    url(r'^get_WareSetupPrefix/$', AdmSector.get_WareSetupPrefix, name='get_WareSetupPrefix'),

    # 订单部分
    url(r'^order/$', views.AdmOrder.as_view(), name='order'),
    url(r'^order/userorder/$', AdmOrder.UserOrder, name='userorder'),
    url(r'^order/setonorder/$', AdmOrder.setOnOrder, name='setonorder'),
    url(r'^order/setAddesOrder/$', AdmOrder.setAddesOrder, name='setaddesorder'),
    url(r'^order/getOrderAcceptanceCheck/$', AdmOrder.getOrderAcceptanceCheck, name='getOrderAcceptanceCheck'),
    url(r'^order/setOrderIspaid$', AdmOrder.setOrderIspaid, name='setOrderIspaid'),
    url(r'^order/contract/$', AdmOrder.ContractView, name='contract'),
    url(r'^order/acceptances/$', AdmOrder.Acceptances, name='acceptances'),
    url(r'^order/delacceptances/$', AdmOrder.delAcceptances, name='delacceptances'),
    url(r'^order/Approval/$', AdmOrder.Approval, name='Approval'),
    url(r'^order/orderCartWare/$', AdmOrder.orderCartWare.as_view(), name='orderCartWare'),

    #
    url(r'^page/$', views.plate.Page, name='page'),
    url(r'^page/create/$', AdmPage.Page_createView, name='page_create'),
    url(r'^page/navplate/$', AdmPage.Page_NavPlate, name='navplate'),
    url(r'^page/navkeyword/$', AdmPage.Page_NavWareAppKeyword, name='navkeyword'),
    url(r'^page/get_navaid/$', AdmPage.get_navaid, name='get_navaid'),

    path('plate/', AdmPlate.IndexView.as_view(), name='AdmPlate')

]

templates/defaule/admin/sector/setupBrand.html
{% extends 'defaule/admin/temp/index.ht' %}
{% load staticfiles %}
{% load tags %}

<!--网站标题-->
{% block main_title %}
   <title>后台管理 | 板块 - 品牌预设</title>
{% endblock main_title %}

<!--CSS样式-->
{% block main_css %}
    <link rel="stylesheet" href="{% static 'select2/dist/css/select2.min.css' %}">
    {% include 'defaule/admin/temp/css.ht' %}
{% endblock main_css %}

<!--网站头部导航栏-->
{% block main_header %}
    <a href="" class="logo">
        <span class="logo-mini"><b>管理</b>Admin</span>
        <span class="logo-lg"><b>后台管理</b>Admin</span>
    </a>
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Admin</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'admins:index' %}">常用 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">创始人</a></li>
                <li><a href="{% url 'admins:complete' %}">全局</a></li>
                <li><a href="{% url 'admins:user' %}">用户</a></li>
                <li><a href="{% url 'admins:commodity' %}">商品</a></li>
                <li><a href="{% url 'admins:order' %}">订单</a></li>
                <li class="active"><a href="{% url 'admins:sector' %}">板块</a></li>
                <li><a href="{% url 'admins:AdmPlate' %}">导航</a></li>
                <li><a href="#">移动APP</a></li>
            </ul>

        </div>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src={% static "images/user/user2-160x160.jpg" %} class="user-image" alt="User Image">
                        <span class="hidden-xs">
                        {{username}}
                        </span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src={% static "images/user/user2-160x160.jpg" %} class="img-circle" alt="User Image">
                            <p>
                                Alexander Pierce - Web Developer
                                <small>Member since Nov. 2012</small>
                            </p>
                        </li>
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="#" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
{% endblock main_header %}

<!--网站左侧项目栏-->
{% block main_aside %}
    <div class="user-panel">
        <div class="pull-left image">
            <img src={% static "images/user/user2-160x160.jpg" %} class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
            <p>{{username}}</p>
            {% if username %}
                <a href="#">
                    <i class="fa fa-circle text-success"></i>
                    管理员
                </a>
            {% endif %}
        </div>
    </div>
    <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="你想知道什么...">
            <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                    <i class="fa fa-search"></i>
                </button>
            </span>
        </div>
    </form>

    <ul class="sidebar-menu" data-widget="tree">
        <li class="header"></li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-laptop"></i>
                <span>首页管理</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li><a href='{% url "admins:sector" %}'><i class="fa fa-circle-o"></i> 板块管理</a></li>
                <li><a href='{% url "admins:classify" %}'><i class="fa fa-circle-o"></i> 全部分类</a></li>
                <li><a href='{% url "admins:navigation" %}'><i class="fa fa-circle-o"></i> 导航管理</a></li>
                <li><a href='{% url "admins:broadcast" %}'><i class="fa fa-circle-o"></i> 轮播/横幅</a></li>
            </ul>
        </li>
        <li class="treeview active">
            <a href="#">
                <i class="fa fa-laptop"></i>
                <span>预设管理</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li><a href='{% url "admins:setupsearch" %}'><i class="fa fa-circle-o"></i> 商品筛选器</a></li>
                <li class="active"><a href='{% url "admins:setupparameter" %}'><i class="fa fa-circle-o"></i> 品牌预设</a></li>
                <li><a href='{% url "admins:discount" %}'><i class="fa fa-circle-o"></i> 优惠率</a></li>
            </ul>
        </li>
    </ul>
{% endblock main_aside %}

<!--正文微标题，位置导航-->
{% block main_content_header %}
    <h1>品牌预设<small>您可以在这里管理或添加相关的品牌预设</small></h1>
    <ol class="breadcrumb">
        <li><a href="{% url 'admins:index' %}"><i class="fa fa-dashboard"></i> 后台首页</a></li>
        <li><a href="{% url 'admins:sector' %}">板块</a></li>
        <li><a href="{% url 'admins:setupbrand' %}">品牌预设</a></li>
        <li class="active">当前位置</li>
    </ol>
{% endblock main_content_header %}

<!--正文开始部分-->
{% block main_content %}

    <div class="row">
        <div id="error"></div>
        <div class="col-md-4">
            <div class="box box-info">
                <div class="box-header">
                    <h4 class="box-title">添加品牌分类</h4>
                </div>
                <div class="box-body">
                    <form id="from_add_filter">
                        <div class="form-group">
                            <label>品牌名称</label>
                            <input type="text" class="form-control" name="name" placeholder="品牌名称">
                        </div>
                        <div class="form-group">
                            <label>归类于一级分类</label>
                            <select name="filter_id" class="form-control select2" style="width: 100%;">
                                {% for var1 in classify %}
                                    <option value="{{var1.id}}">{{var1.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div id="error_filter"></div>
                        <div class="box-footer pull-right">
                            <button type="submit" class="btn btn-info">创建</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock main_content %}

<!--位置底部Footer信息-->
{% block main_footer %}
    {% include 'defaule/admin/temp/footer.ht' %}
{% endblock main_footer %}

<!--网站Script脚本-->
{% block main_script %}

    {% include 'defaule/admin/temp/script.ht' %}
    <script src="{% static 'select2/dist/js/select2.full.min.js' %}"></script>
    <script src="{% static 'js/csrf_token.js' %}"></script>
    <script>
        $('.select2').select2()

        var from_add_filter = document.getElementById("from_add_filter") //添加筛选器

        function submitFormAddFilter(urls, froms){
            var Dat = new FormData(froms)
            var url = urls;
            var D = {
                "name": Dat.get('name'),
                "classify_id": Dat.get('filter_id')
            }
            setPOST(url, D, 'error_filter');
            console.log(D);
        }

        from_add_filter.addEventListener("submit", function (event) {
            event.preventDefault();   // 取消按键的原始提交行为
            submitFormAddFilter("{% url 'admins:add_brand' %}", from_add_filter);         //启动监听提交按钮
        });
    </script>


{% endblock main_script %}